FROM node:10.17-jessie

RUN apt-get update
RUN apt-get install -y lsb-release
RUN wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
RUN dpkg -i couchbase-release-1.0-6-amd64.deb
RUN apt-get update && apt-get install -y libcouchbase-dev libcouchbase2-bin build-essential

WORKDIR /app

COPY ./package.json ./

RUN npm install

#make sure to not copy of node_modules folder
#that will lead to problems
#https://stackoverflow.com/questions/34822326/invalid-elf-header-node-js-with-couchbase-db
COPY . .

ENV API_PORT 3000

CMD ["npm", "run", "dev"]