#CBS is only supported on debian 8x (jessie) and 9x (stretch) as of 2020-07-xx
#   and supports LTS node 12.18.x
#https://docs.couchbase.com/nodejs-sdk/2.6/start-using-sdk.html
FROM node:12.18.2-stretch-slim

RUN apt-get update
RUN apt-get install -y lsb-release wget
#LCB installation
RUN wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
RUN dpkg -i couchbase-release-1.0-6-amd64.deb
RUN apt-get update && apt-get install -y libcouchbase-dev libcouchbase2-bin build-essential
#If needing curl or python
RUN apt-get install -y curl jq

WORKDIR /app

COPY ./package.json ./

RUN npm install

#make sure to not copy of node_modules folder -> can lead to problems
#https://stackoverflow.com/questions/34822326/invalid-elf-header-node-js-with-couchbase-db
COPY . .

RUN chmod +x /app/resources/catchup.sh

ENV API_PORT 3000

CMD ["npm", "run", "dev"]